#!/usr/bin/env node
/**
 * score.mjs — the one computation behind `map`'s dashboard and scoreboard.
 *
 * `data/_views/blind-spots.md` already holds the extracted layer's fractions (screens routed,
 * typed tables reached, edge functions mapped, ...) and `flows.mjs` already computes the authored
 * layer's (surfaces claimed by a feature, features with a flow, flows authored) — see that file's
 * `loadMapTables`/`computeAuthoredCoverage`, which this module calls rather than re-deriving the
 * same join. Two readers of one number is the drift this whole system exists to prevent;
 * `computeScore` below is the *only* place that combines the two layers plus `data/resources/`,
 * and `scripts/serve.mjs` is the *only* caller — both its stdout scoreboard and its dashboard
 * server's request handler call this one function, never a second computation of their own.
 *
 * `computeScore` reads `data/` off disk on every call and caches nothing, on purpose: the
 * dashboard calls it fresh per HTTP request so editing a row and reloading shows the change
 * without restarting the server (see scripts/serve.mjs). Nothing here embeds the current time.
 *
 * Node built-ins only, no dependencies.
 */
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { computeAuthoredCoverage, listFiles, loadMapTables, parseFrontmatter } from "./flows.mjs";

const BLIND_SPOTS_FILE = "data/_views/blind-spots.md";

/** data/resources/ isn't read by flows.mjs, so this reuses its exported frontmatter reader
 *  (parseFrontmatter, listFiles) rather than writing a second one — one reader for the whole map. */
function loadResources(root) {
  const dir = join(root, "data/resources");
  const rows = listFiles(dir).map((f) => {
    const fm = parseFrontmatter(readFileSync(join(dir, f), "utf8"), `resources/${f}`);
    return {
      id: fm.id,
      name: fm.name,
      backing: fm.backing,
      declared: fm.declared,
      scope: fm.scope,
      debt: fm.debt,
      rls_enabled: fm.rls_enabled,
      rls: fm.rls ?? [],
      reach: fm.reach || "none",
      used_by: fm.used_by ?? [],
      fields: fm.fields ?? [],
      claimed_by: fm.claimed_by ?? [],
    };
  });
  rows.sort((a, b) => a.id.localeCompare(b.id));
  return rows;
}

/**
 * Parses the `data/_views/blind-spots.md` fenced block into `{ label, num, den, note }` rows.
 * That file is itself GENERATED by `map sync` (see its own footer comment) — this only reads it,
 * never recomputes a blind-spot count from source, which would be exactly the second reader this
 * module exists to avoid. Absent (`map sync` never run here) is not an error: it returns `[]` and
 * callers render an explanatory empty state instead of crashing.
 */
function loadExtractedFractions(root) {
  let text;
  try {
    text = readFileSync(join(root, BLIND_SPOTS_FILE), "utf8");
  } catch {
    return [];
  }
  const block = /```text\r?\n([\s\S]*?)```/.exec(text);
  if (!block) return [];
  const rows = [];
  for (const line of block[1].split(/\r?\n/)) {
    if (!line.trim()) continue;
    // "<label>   <num> / <den>   <note>" — columns are whitespace-aligned by the generator, so
    // two-or-more spaces is the field separator (see data/_views/blind-spots.md).
    const m = /^(.+?)\s{2,}(\d+)\s*\/\s*(\d+)\s{2,}(.*)$/.exec(line);
    if (!m) continue;
    rows.push({ label: m[1].trim(), num: Number(m[2]), den: Number(m[3]), note: m[4].trim() });
  }
  return rows;
}

/**
 * The one computation. Returns:
 *   - errors: problems loadMapTables found (duplicate ids, a step naming a surface that doesn't
 *     exist, ...) — non-empty only when the working tree is in a state `map check` would already
 *     reject. `authored` is null when this is non-empty; `resources`/`extracted` still populate,
 *     since those tables don't depend on flows/features/surfaces resolving.
 *   - authored: the featuresTotal/surfacesTotal/... fractions `map flows`'s own stdout line and
 *     docs/USER-FLOWS.md's Coverage section already show — same numbers, same function.
 *   - extracted: the data/_views/blind-spots.md rows, verbatim.
 *   - features/surfaces/flows/resources: the raw sorted rows, for the dashboard's tables.
 */
export function computeScore(root = process.cwd()) {
  const { featuresSorted, surfacesSorted, flows, errors } = loadMapTables(root);
  const resources = loadResources(root);
  const extracted = loadExtractedFractions(root);

  if (errors.length > 0) {
    return {
      errors,
      authored: null,
      extracted,
      features: featuresSorted,
      surfaces: surfacesSorted,
      flows,
      resources,
      coverage: null,
    };
  }

  const coverage = computeAuthoredCoverage({ featuresSorted, surfacesSorted, flows });
  const authored = {
    surfacesClaimed: coverage.claimedSurfaces.length,
    surfacesTotal: coverage.surfacesTotal,
    featuresWithFlow: coverage.featuresWithFlows.size,
    featuresTotal: coverage.featuresTotal,
    flowsTotal: coverage.flowsTotal,
  };

  return {
    errors: [],
    authored,
    extracted,
    features: featuresSorted,
    surfaces: surfacesSorted,
    flows,
    resources,
    coverage,
  };
}

function pct(num, den) {
  return den === 0 ? null : Math.round((num / den) * 100);
}

/** Every fraction, as one block — the headless-safe half of `map`. Same `score` object
 *  (from `computeScore`) the dashboard renders, formatted for a terminal instead of a browser. */
export function formatScoreboard(score) {
  const lines = [];
  const p = (s = "") => lines.push(s);
  const row = (label, num, den) => {
    const p_ = pct(num, den);
    p(`    ${label.padEnd(34)} ${String(num).padStart(3)} / ${den}  (${p_ === null ? "—" : `${p_}%`})`);
  };

  p("Map score");
  p();
  if (score.errors.length > 0) {
    p("  authored — NOT computed, data/flows|features|surfaces don't resolve:");
    for (const e of score.errors) p(`    - ${e}`);
  } else {
    p("  authored  (data/features/, data/surfaces/, data/flows/ — joined by flows.mjs)");
    row("surfaces claimed by a feature", score.authored.surfacesClaimed, score.authored.surfacesTotal);
    row("features with a flow", score.authored.featuresWithFlow, score.authored.featuresTotal);
    p(`    ${"flows authored".padEnd(34)} ${score.authored.flowsTotal}`);
  }
  p();
  if (score.extracted.length > 0) {
    p("  extracted  (data/_views/blind-spots.md — written by map sync)");
    for (const r of score.extracted) row(r.label, r.num, r.den);
  } else {
    p("  extracted  (data/_views/blind-spots.md) — not found; run map sync to populate it");
  }
  p();
  return lines.join("\n");
}
